project:
  type: website

website:
  title: ""
  site-url: https://dhammarstrom.github.io
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: Publications
        href: publications.qmd
      - text: Projects
        href: projects.qmd
      - text: Teaching
        href: teaching.qmd
      - text: Software
        href: software.qmd
      - text: Blog
        href: blog.qmd
      - text: CV
        href: cv.qmd
    right:
      - icon: github
        href: https://github.com/dhammarstrom
        aria-label: GitHub
      - icon: bluesky
        href: https://bsky.app/profile/dhammarstrom.bsky.social
        aria-label: Bluesky
      - icon: rss
        href: blog.xml
        aria-label: RSS

format:
  html:
    theme: [brand, styles-publications.scss, styles-index.scss, styles-banner.scss]
    toc: true
    include-after-body: _includes/graph-banner.html
