---
title: "Daniel Hammarström"
listing:
  contents: posts
  sort: "date desc"
  type: default
  categories: true
  sort-ui: false
  filter-ui: false
page-layout: full
title-block-banner: true
---

::: {.grid}

::: {.g-col-6}

A profile picture

:::

::: {.g-col-6}
# About
I'm an Associate Professor at the [Inland University of Applied Sciences](https://www.inn.no), where my research interests revolves around uncovering factors that contribute to the diverse responses individuals exhibit to exercise training. My investigative approach is interdisciplinary, weaving together physiology, statistical methods and bioinformatics in  studies of exercise training.

In the realm of academics, I am involved in teaching research methods with focus on statistics and molecular biology as part of our Health and Exercise Physiology Master's program. Additionally, I mentor students at various levels, overseeing the academic and research progression of Bachelor's, Master's, and Ph.D. candidates.

I'm part of the [trainome research group](trainome.github.io), collectively we want to better understand why and how people responds to exercise training and find out how we can design better exercise training interventions for different populations.

You can read my blog below or find me on [Twitter](https://twitter.com/dhammarstrom), [Mastodon](https://mastodon.social/@dhammarstrom) or
[GitHub](https://github.com/dhammarstrom).


:::

:::
